### ISSUE TITLE
Spekpy issue

### ISSUE THREAD

**Issue by justingm** [jerichooconnell/fastcat#17]
Hi!

I am trying out the advanced demo but I am getting an error generating a spectra from Spekpy.
![Screenshot 2022-05-12 at 13 06 18](https://user-images.githubusercontent.com/72226803/168060378-9db0d6be-5a38-497d-9eea-fa7cd85bb4c3.png)

I am not sure if it is just an installation issue on my side.

**Comment by justingm** [comment]
By the way, I added shift=None to the parameters in Spekpy (found in spectrum.py) to make it work. I am not sure if I'm the only one getting this error but that's how I solved it.

**Comment by jerichooconnell** [comment]
You can just generate a spectrum by importing spekpy and then setting spectrum.x and spectrum.y in the fastcat spectrum object if you like. That is about all the spectrum object is looking for
