### ISSUE TITLE
Question about the detector size

### ISSUE THREAD

**Issue by justingm** [jerichooconnell/fastcat#19]
Is it not allowed to have number of pixels greater than 512 in x  (or maybe u is the right convention)? I'm getting an error if I do that and I understand that you've set this limitation because of memory issues but I have a pretty good computer so I think it should be fine. I am wondering if that could be extended because I'm using the 150 um pixel pitch so the total size of the detector would be too small for certain magnifications or if I have larger objects (like maybe a rat). In the paper you mentioned that you also did 1024 x 1024 x 10 reconstructions so I guess it is possible.

**Comment by jerichooconnell** [comment]
And then the detector convolutions have to be sampled correctly as they are generally made on a 512x512

**Comment by jerichooconnell** [comment]
I'm not sure if all of that works anymore I'll have to do some testing

**Comment by jerichooconnell** [comment]
Would you like write access to the Repo? I could make you a co-owner if you have interest in fiddling with things
