### ISSUE TITLE
Generating synthetic CBCT projections from a specified 3D object model

### ISSUE THREAD

**Issue by qbeer** [jerichooconnell/fastcat#20]
Hi,

 I have a very specific 'request/question': I want to generate synthetic projections of an organ (e.g) from multiple views. In order to do this, I want to synthesize such projections with the correct physical imaging model. Would this be possible with this framework? Would you have time to discuss this further in email maybe: olar.alex at complex.elte.hu

 What I've found so far, but have been used for CTs is: https://gitlab.com/plastimatch/plastimatch

Thanks in advance,
Alex

**Comment by jerichooconnell** [comment]
Yes it is possible to do this with this framework, however it is not completely straightforward to import a new phantom. To do this you need to convert the attenuation coefficients to integers and assign them a material
